version: '3'
services:
  web:
    container_name: web
    build: ./docker/web
    working_dir: /etc/nginx
    ports:
      - 80:80
    volumes:
      - django-static:/var/www/html/static
    links:
      - app
    restart: "on-failure"

  app:
    container_name: app
    build: .
    working_dir: /django_project
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      ALLOWED_HOSTS: $ALLOWED_HOSTS
    volumes:
      - django-static:/var/www/html/static
      - ./data:/django_project/data:rw
    restart: "on-failure"

volumes:
  django-static:
